version: '3.8'
services:
  form:
    image: onao13/form
    networks:
      - dev
    depends_on:
      - db
    ports:
      - "8150:8150"
  db:
    image: postgres:latest
    env_file:
      - db.env
    volumes:
      - /db:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"
volumes:
  db:
networks:
  dev: